jetstream {
  store_dir: /data
  max_mem_store: 256MB
  max_file_store: 10GB
}

max_payload: 8MB
monitor_port: 8222

authorization {
  users = [
    {
      user: $NATS_BOT_USER
      password: $NATS_BOT_PASSWORD_BCRYPT
      permissions: {
        publish: ["events.messages", "$JS.API.>", "$JS.ACK.>", "$KV.ratelimit.>"]
        subscribe: ["events.replies", "_INBOX.>", "$KV.ratelimit.>"]
      }
    },
    {
      user: $NATS_WORKER_USER
      password: $NATS_WORKER_PASSWORD_BCRYPT
      permissions: {
        publish: ["events.replies", "$JS.API.>", "$JS.ACK.>", "$KV.history.>"]
        subscribe: ["events.messages", "_INBOX.>", "$KV.history.>"]
      }
    },
    {
      user: $NATS_API_USER
      password: $NATS_API_PASSWORD_BCRYPT
      permissions: {
        publish: [">"]
        subscribe: [">"]
      }
    }
  ]
}
